"""Claude AI report generation — structured credit memo output.

COMPLIANCE:
- RBI Guidelines: CreditMemo.disclaimer MUST be present in every report
- All external data is sanitized before entering LLM context (prompt injection defense)
- Model version and SHAP factors must be traceable

SECURITY:
- Never pass raw user input to LLM without sanitization
- Never expose API keys in responses or logs
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any

import httpx

from src.core.config import get_settings
from src.core.logging import logger
from src.core.utils import format_currency_inr, sanitize_for_llm_context
from src.scoring.model import ScoringResult
from src.scoring.repositories import GSTINData


@dataclass
class CreditMemo:
    """Structured credit memo — output of the Claude report generator.

    COMPLIANCE NOTE: RBI mandates that all AI-assisted credit decisions
    include a disclaimer, model version, and explainability data.
    """

    gstin: str
    legal_name: str
    trade_name: str
    vri_score: int
    risk_grade: str
    probability_of_default: float

    executive_summary: str
    business_overview: str
    financial_analysis: str
    risk_factors: str
    strengths: str
    recommendation: str

    shap_top_factors: list[dict[str, Any]] = field(default_factory=list)

    # Compliance metadata
    model_version: str = "demo-v1.0"
    generated_at: str = ""
    disclaimer: str = (
        "This credit assessment is generated by an AI system and is intended as a "
        "decision-support tool only. It should not be used as the sole basis for credit "
        "decisions. All assessments must be reviewed by qualified credit officers in "
        "accordance with RBI Master Direction on Digital Lending (RBI/2022-23/111) and "
        "institutional credit policies."
    )

    def __post_init__(self) -> None:
        if not self.generated_at:
            self.generated_at = datetime.now(timezone.utc).isoformat()


class ReportGenerator:
    """Generates structured credit memos using Claude API.

    Design decisions:
    - Uses claude-sonnet-4-20250514 for speed/cost balance (switch to opus for production)
    - Structured output via JSON schema enforcement
    - Sanitizes ALL external data before LLM context
    """

    CLAUDE_MODEL = "claude-sonnet-4-20250514"
    MAX_TOKENS = 2000

    def __init__(self) -> None:
        self.settings = get_settings()

    async def generate(self, scoring: ScoringResult, gstin_data: GSTINData) -> CreditMemo:
        """Generate a full credit memo from scoring result + GSTIN data.

        Falls back to a template-based report if Claude API is unavailable.
        """
        if not self.settings.anthropic_api_key:
            logger.warning("No Anthropic API key configured — using template fallback.")
            return self._generate_template_report(scoring, gstin_data)

        try:
            return await self._generate_claude_report(scoring, gstin_data)
        except Exception as e:
            logger.error("Claude API call failed: %s — falling back to template.", str(e))
            return self._generate_template_report(scoring, gstin_data)

    async def _generate_claude_report(
        self, scoring: ScoringResult, gstin_data: GSTINData
    ) -> CreditMemo:
        """Call Claude API with structured prompt."""
        prompt = self._build_prompt(scoring, gstin_data)

        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.post(
                "https://api.anthropic.com/v1/messages",
                headers={
                    "x-api-key": self.settings.anthropic_api_key,
                    "anthropic-version": "2023-06-01",
                    "content-type": "application/json",
                },
                json={
                    "model": self.CLAUDE_MODEL,
                    "max_tokens": self.MAX_TOKENS,
                    "messages": [
                        {"role": "user", "content": prompt},
                    ],
                    "system": (
                        "You are a senior credit analyst at a leading Indian NBFC. "
                        "You produce concise, data-driven credit memos for MSME borrowers. "
                        "Your analysis follows RBI guidelines and institutional credit policies. "
                        "Respond ONLY with valid JSON matching the exact schema provided."
                    ),
                },
            )
            response.raise_for_status()
            result = response.json()

        # Parse Claude's response
        content = result["content"][0]["text"]
        # Strip markdown code fences if present
        content = content.strip()
        if content.startswith("```json"):
            content = content[7:]
        if content.startswith("```"):
            content = content[3:]
        if content.endswith("```"):
            content = content[:-3]
        content = content.strip()

        parsed = json.loads(content)

        return CreditMemo(
            gstin=gstin_data.gstin,
            legal_name=gstin_data.legal_name,
            trade_name=gstin_data.trade_name,
            vri_score=scoring.vri_score,
            risk_grade=scoring.risk_grade,
            probability_of_default=scoring.probability_of_default,
            executive_summary=parsed.get("executive_summary", ""),
            business_overview=parsed.get("business_overview", ""),
            financial_analysis=parsed.get("financial_analysis", ""),
            risk_factors=parsed.get("risk_factors", ""),
            strengths=parsed.get("strengths", ""),
            recommendation=parsed.get("recommendation", ""),
            shap_top_factors=[
                {
                    "feature": f.feature,
                    "display_name": f.display_name,
                    "value": f.value,
                    "shap_value": f.shap_value,
                    "direction": f.direction,
                    "magnitude": f.magnitude,
                }
                for f in scoring.shap_factors
            ],
            model_version=scoring.model_version,
        )

    def _build_prompt(self, scoring: ScoringResult, gstin_data: GSTINData) -> str:
        """Build the structured prompt for Claude.

        SECURITY: All data is sanitized before entering the prompt.
        """
        # Sanitize all text fields
        s = sanitize_for_llm_context
        litigation_text = "; ".join(s(f) for f in gstin_data.litigation_flags) if gstin_data.litigation_flags else "None"

        shap_text = "\n".join(
            f"  - {f.display_name}: SHAP={f.shap_value:+.4f} ({f.direction}, {f.magnitude} impact) "
            f"[value={f.value:.4f}]"
            for f in scoring.shap_factors[:8]
        )

        quarterly_text = ", ".join(
            format_currency_inr(q) for q in gstin_data.quarterly_revenue
        )

        return f"""Analyze this MSME borrower and generate a structured credit memo.

## BUSINESS DATA
- Legal Name: {s(gstin_data.legal_name)}
- Trade Name: {s(gstin_data.trade_name)}
- GSTIN: {gstin_data.gstin}
- Business Type: {s(gstin_data.business_type)}
- Sector: {s(gstin_data.sector)} / {s(gstin_data.sub_sector)}
- Status: {gstin_data.status}
- Years in Business: {gstin_data.years_in_business}
- Employees (est.): {gstin_data.employee_count_est}

## FINANCIAL DATA
- Avg Monthly Revenue: {format_currency_inr(gstin_data.avg_monthly_revenue)}
- Revenue Trend: {gstin_data.revenue_trend_pct:+.1f}%
- Quarterly Revenue (Q1→Q4): {quarterly_text}
- Tax Paid (12m): {format_currency_inr(gstin_data.total_tax_paid_12m)}

## GST COMPLIANCE
- Returns Filed (12m): {gstin_data.returns_filed_12m}/12
- Nil Returns: {gstin_data.nil_returns_12m}
- Late Returns: {gstin_data.late_returns_12m}

## CREDIT HISTORY
- Existing Loans: {gstin_data.existing_loans}
- Total Outstanding: {format_currency_inr(gstin_data.total_outstanding)}
- DPD 30+: {gstin_data.dpd_30_count}, DPD 60+: {gstin_data.dpd_60_count}, DPD 90+: {gstin_data.dpd_90_count}
- Credit Utilization: {gstin_data.credit_utilization_pct}%

## RISK SIGNALS
- Litigations: {litigation_text}
- Compliance Notices: {gstin_data.compliance_notices}

## AI SCORING OUTPUT
- VRI Score: {scoring.vri_score}/1000 (Grade: {scoring.risk_grade})
- Probability of Default: {scoring.probability_of_default:.2%}
- Top SHAP Drivers:
{shap_text}

## REQUIRED OUTPUT (JSON ONLY)
Return a JSON object with exactly these keys:
```json
{{
  "executive_summary": "3-4 sentences summarizing the credit worthiness",
  "business_overview": "2-3 sentences on business profile and market position",
  "financial_analysis": "3-4 sentences analyzing revenue, growth, and financial health",
  "risk_factors": "2-3 sentences on key risk concerns",
  "strengths": "2-3 sentences on positive factors supporting creditworthiness",
  "recommendation": "Clear APPROVE / CONDITIONAL APPROVE / REJECT with terms"
}}
```
"""

    def _generate_template_report(
        self, scoring: ScoringResult, gstin_data: GSTINData
    ) -> CreditMemo:
        """Template-based fallback — no LLM needed. For local dev without API key."""
        is_good = scoring.vri_score >= 600
        is_borderline = 400 <= scoring.vri_score < 600
        is_bad = scoring.vri_score < 400

        if is_good:
            summary = (
                f"{gstin_data.trade_name} demonstrates strong creditworthiness with a VRI score of "
                f"{scoring.vri_score}/1000 (Grade {scoring.risk_grade}). The business shows consistent "
                f"GST compliance, stable revenue growth of {gstin_data.revenue_trend_pct:+.1f}%, and "
                f"a healthy credit utilization of {gstin_data.credit_utilization_pct}%."
            )
            recommendation = (
                f"APPROVE — Recommended credit limit up to "
                f"{format_currency_inr(gstin_data.avg_monthly_revenue * 3)} with standard terms."
            )
        elif is_borderline:
            summary = (
                f"{gstin_data.trade_name} presents a borderline credit profile with a VRI score of "
                f"{scoring.vri_score}/1000 (Grade {scoring.risk_grade}). While the business has "
                f"operational history, certain risk factors warrant enhanced due diligence."
            )
            recommendation = (
                f"CONDITIONAL APPROVE — Reduced credit limit up to "
                f"{format_currency_inr(gstin_data.avg_monthly_revenue * 1.5)} "
                f"with enhanced monitoring and quarterly review."
            )
        else:
            summary = (
                f"{gstin_data.trade_name} presents significant credit risk with a VRI score of "
                f"{scoring.vri_score}/1000 (Grade {scoring.risk_grade}). Multiple risk factors "
                f"including {'high debt levels, ' if gstin_data.credit_utilization_pct > 75 else ''}"
                f"{'declining revenue, ' if gstin_data.revenue_trend_pct < -10 else ''}"
                f"indicate elevated default probability."
            )
            recommendation = "REJECT — Credit application does not meet minimum eligibility criteria at this time."

        return CreditMemo(
            gstin=gstin_data.gstin,
            legal_name=gstin_data.legal_name,
            trade_name=gstin_data.trade_name,
            vri_score=scoring.vri_score,
            risk_grade=scoring.risk_grade,
            probability_of_default=scoring.probability_of_default,
            executive_summary=summary,
            business_overview=(
                f"{gstin_data.trade_name} ({gstin_data.legal_name}) is a {gstin_data.business_type} "
                f"operating in {gstin_data.sector}/{gstin_data.sub_sector} since "
                f"{gstin_data.registration_date}. The business employs approximately "
                f"{gstin_data.employee_count_est} people and generates average monthly revenue of "
                f"{format_currency_inr(gstin_data.avg_monthly_revenue)}."
            ),
            financial_analysis=(
                f"Annual revenue stands at approximately {format_currency_inr(gstin_data.avg_monthly_revenue * 12)} "
                f"with a year-over-year trend of {gstin_data.revenue_trend_pct:+.1f}%. "
                f"GST compliance is {'strong' if gstin_data.returns_filed_12m >= 10 else 'moderate' if gstin_data.returns_filed_12m >= 7 else 'weak'} "
                f"with {gstin_data.returns_filed_12m}/12 returns filed on time. "
                f"Total tax paid in the last 12 months is {format_currency_inr(gstin_data.total_tax_paid_12m)}, "
                f"indicating {'consistent' if gstin_data.nil_returns_12m <= 1 else 'inconsistent'} business activity."
            ),
            risk_factors=(
                f"Key risk factors include: credit utilization at {gstin_data.credit_utilization_pct}%, "
                f"{gstin_data.existing_loans} existing loans with total outstanding of "
                f"{format_currency_inr(gstin_data.total_outstanding)}. "
                f"{'Active litigation(s) noted. ' if gstin_data.litigation_flags else ''}"
                f"{'DPD events detected in credit history. ' if gstin_data.dpd_30_count > 0 else ''}"
                f"{'GST registration is not Active — major red flag.' if gstin_data.status != 'Active' else ''}"
            ),
            strengths=(
                f"Positive indicators: {gstin_data.years_in_business:.1f} years of operational history, "
                f"{'strong GST filing compliance, ' if gstin_data.returns_filed_12m >= 10 else ''}"
                f"{'positive revenue growth trend, ' if gstin_data.revenue_trend_pct > 10 else ''}"
                f"{'clean litigation record, ' if not gstin_data.litigation_flags else ''}"
                f"{'low credit utilization' if gstin_data.credit_utilization_pct < 50 else 'established banking relationship'}."
            ),
            recommendation=recommendation,
            shap_top_factors=[
                {
                    "feature": f.feature,
                    "display_name": f.display_name,
                    "value": f.value,
                    "shap_value": f.shap_value,
                    "direction": f.direction,
                    "magnitude": f.magnitude,
                }
                for f in scoring.shap_factors
            ],
            model_version=scoring.model_version,
        )
